// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/setup": {
    params: {};
  };
  "/cert": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/api/packets": {
    params: {};
  };
  "/api/packets/:id": {
    params: {
      "id": string;
    };
  };
  "/api/replay/:id": {
    params: {
      "id": string;
    };
  };
  "/api/intercept/:id": {
    params: {
      "id": string;
    };
  };
  "/api/har": {
    params: {};
  };
  "/api/session": {
    params: {};
  };
  "/api/ca": {
    params: {};
  };
  "/api/stats": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/setup" | "/cert" | "/settings" | "/api/packets" | "/api/packets/:id" | "/api/replay/:id" | "/api/intercept/:id" | "/api/har" | "/api/session" | "/api/ca" | "/api/stats";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/setup.tsx": {
    id: "routes/setup";
    page: "/setup";
  };
  "routes/cert.tsx": {
    id: "routes/cert";
    page: "/cert";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/api.packets.ts": {
    id: "routes/api.packets";
    page: "/api/packets";
  };
  "routes/api.packets.$id.ts": {
    id: "routes/api.packets.$id";
    page: "/api/packets/:id";
  };
  "routes/api.replay.$id.ts": {
    id: "routes/api.replay.$id";
    page: "/api/replay/:id";
  };
  "routes/api.intercept.$id.ts": {
    id: "routes/api.intercept.$id";
    page: "/api/intercept/:id";
  };
  "routes/api.har.ts": {
    id: "routes/api.har";
    page: "/api/har";
  };
  "routes/api.session.ts": {
    id: "routes/api.session";
    page: "/api/session";
  };
  "routes/api.ca.ts": {
    id: "routes/api.ca";
    page: "/api/ca";
  };
  "routes/api.stats.ts": {
    id: "routes/api.stats";
    page: "/api/stats";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/setup": typeof import("./app/routes/setup.tsx");
  "routes/cert": typeof import("./app/routes/cert.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/api.packets": typeof import("./app/routes/api.packets.ts");
  "routes/api.packets.$id": typeof import("./app/routes/api.packets.$id.ts");
  "routes/api.replay.$id": typeof import("./app/routes/api.replay.$id.ts");
  "routes/api.intercept.$id": typeof import("./app/routes/api.intercept.$id.ts");
  "routes/api.har": typeof import("./app/routes/api.har.ts");
  "routes/api.session": typeof import("./app/routes/api.session.ts");
  "routes/api.ca": typeof import("./app/routes/api.ca.ts");
  "routes/api.stats": typeof import("./app/routes/api.stats.ts");
};